const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const cp = require("node:child_process");
const ts = require("typescript");
const { z } = require("zod");

const repository = path.resolve(__dirname, "..");
// Synthetic repositories exercise the real checker without touching a user's checkout.
const rootIndex = process.argv.indexOf("--root");
const root = rootIndex === -1 ? repository : path.resolve(process.argv[rootIndex + 1]);
const write = process.argv.includes("--write");
const errors = [];
const read = (file) => fs.readFileSync(path.join(root, file), "utf8").replace(/\r\n/g, "\n");
const source = (file) => ts.createSourceFile(file, read(file), ts.ScriptTarget.Latest, true);
const visit = (node, callback) => {
  callback(node);
  ts.forEachChild(node, (child) => visit(child, callback));
};
const text = (node, sf) => node.getText(sf);
const evaluate = (node, sf, context) =>
  vm.runInNewContext(
    ts.transpileModule(`(${text(node, sf)})`, {
      compilerOptions: { target: ts.ScriptTarget.ES2022 },
    }).outputText,
    context,
    { timeout: 1000 },
  );
const exported = (node) => node.modifiers?.some((mod) => mod.kind === ts.SyntaxKind.ExportKeyword);
const link = (file, line) =>
  `https://github.com/doodlum/vortex-doodlebot/blob/main/${file}${line ? "#L" + line : ""}`;
const banner = (audience) =>
  `<!-- Generated by pnpm run docs:generate. Edit the implementation, then regenerate both audiences. -->\n\n${audience}\n\n`;

function tools() {
  const sf = source("src/mcpServer.ts");
  const calls = new Map();
  for (const node of sf.statements) {
    if (!ts.isFunctionDeclaration(node) || !node.name) continue;
    const children = new Set();
    visit(node, (child) => {
      if (
        ts.isCallExpression(child) &&
        ts.isIdentifier(child.expression) &&
        /^register.+Tools?$/.test(child.expression.text)
      )
        children.add(child.expression.text);
    });
    calls.set(node.name.text, children);
  }
  const reachable = (start) => {
    const found = new Set();
    const collect = (name) => {
      if (found.has(name)) return;
      found.add(name);
      for (const child of calls.get(name) ?? []) collect(child);
    };
    collect(start);
    return found;
  };
  const reads = reachable("registerReadTools");
  const writes = reachable("registerWriteTools");
  const context = { z };
  visit(sf, (node) => {
    if (
      ts.isVariableDeclaration(node) &&
      ["expectedContextSchema", "uiTargetSchema"].includes(node.name.getText(sf))
    )
      context[node.name.getText(sf)] = evaluate(node.initializer, sf, context);
  });
  const records = [];
  visit(sf, (node) => {
    if (
      !ts.isCallExpression(node) ||
      !ts.isPropertyAccessExpression(node.expression) ||
      node.expression.name.text !== "registerTool"
    )
      return;
    const name = evaluate(node.arguments[0], sf, context);
    const metadata = evaluate(node.arguments[1], sf, context);
    let parent = node.parent;
    while (parent && !ts.isFunctionDeclaration(parent)) parent = parent.parent;
    const registration = parent?.name?.text;
    if (!registration) throw new Error(`Cannot identify registration for ${name}`);
    if (!reads.has(registration) && !writes.has(registration))
      throw new Error(`Unclassified registration for ${name}: ${registration}`);
    // Descriptions are plain tool strings, not Markdown. Preserve literals such as
    // __CALLBACK__ instead of letting a formatter turn them into bold text.
    const description = metadata.description.replace(/[\\`*_{}[\]<>#]/g, "\\$&");
    records.push({
      name,
      description,
      inputSchema: z.toJSONSchema(metadata.inputSchema, { unrepresentable: "any" }),
      tokenRequired: writes.has(registration) && !reads.has(registration),
      registration,
      line: sf.getLineAndCharacterOfPosition(node.getStart()).line + 1,
    });
  });
  if (records.length === 0 || new Set(records.map((r) => r.name)).size !== records.length)
    throw new Error("Missing or duplicate MCP registrations");
  return records;
}

function cli() {
  const sf = source("harness/src/cli.ts");
  let help;
  const names = new Set();
  visit(sf, (node) => {
    if (ts.isVariableDeclaration(node) && node.name.getText(sf) === "HELP")
      help = evaluate(node.initializer, sf, {});
    if (
      ts.isBinaryExpression(node) &&
      node.operatorToken.kind === ts.SyntaxKind.EqualsEqualsEqualsToken &&
      node.left.getText(sf) === "command" &&
      ts.isStringLiteral(node.right)
    )
      names.add(node.right.text);
    if (ts.isCaseClause(node) && ts.isStringLiteral(node.expression)) {
      let parent = node.parent;
      while (parent && !ts.isSwitchStatement(parent)) parent = parent.parent;
      if (parent?.expression.getText(sf) === "command") names.add(node.expression.text);
    }
  });
  if (!help || names.size === 0) throw new Error("CLI inventory is empty");
  return { help, commands: [...names].sort() };
}

function api() {
  const entry = source("harness/src/kit.ts");
  const modules = new Map([
    ["config", "config.ts"],
    ["mcpClient", "mcpClient.ts"],
    ["cdp", "cdp.ts"],
    ["instance", "instance.ts"],
    ["jsonFile", "jsonFile.ts"],
  ]);
  for (const statement of entry.statements) {
    if (
      ts.isExportDeclaration(statement) &&
      statement.moduleSpecifier &&
      ts.isNamespaceExport(statement.exportClause)
    )
      modules.set(
        statement.exportClause.name.text,
        statement.moduleSpecifier.text.replace("./", "") + ".ts",
      );
  }
  return [...modules].map(([name, file]) => {
    const relative = "harness/src/" + file;
    const sf = source(relative);
    const symbols = [];
    for (const node of sf.statements) {
      if (!exported(node)) continue;
      let signature;
      if (ts.isFunctionDeclaration(node))
        signature =
          text(node, sf)
            .slice(0, node.body ? node.body.pos - node.getStart() : undefined)
            .trim() + ";";
      else if (ts.isClassDeclaration(node))
        signature =
          `export class ${node.name.text} {\n` +
          node.members
            .filter(
              (m) =>
                !m.name?.getText(sf).startsWith("#") &&
                !m.modifiers?.some((mod) => mod.kind === ts.SyntaxKind.PrivateKeyword),
            )
            .map((m) =>
              m.body
                ? m
                    .getText(sf)
                    .slice(0, m.body.pos - m.getStart())
                    .trim() + ";"
                : m.getText(sf),
            )
            .join("\n") +
          "\n}";
      else if (ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node))
        signature = text(node, sf);
      else if (ts.isVariableStatement(node))
        signature = node.declarationList.declarations
          .filter((d) => ts.isIdentifier(d.name))
          .map((d) => `export const ${d.name.text}${d.type ? ": " + d.type.getText(sf) : ""};`)
          .join("\n");
      else continue;
      const docs = (node.jsDoc ?? [])
        .map((d) => (typeof d.comment === "string" ? d.comment : ""))
        .join("\n");
      symbols.push({
        signature,
        docs,
        line: sf.getLineAndCharacterOfPosition(node.getStart()).line + 1,
      });
    }
    return { name, file: relative, symbols };
  });
}

function result(file, expected) {
  expected = cp.execFileSync(
    process.execPath,
    [path.join(repository, "node_modules/oxfmt/bin/oxfmt"), "--stdin-filepath", file],
    { cwd: root, input: expected, encoding: "utf8", maxBuffer: 10 * 1024 * 1024 },
  );
  if (write) {
    fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    fs.writeFileSync(path.join(root, file), expected);
  } else if (!fs.existsSync(path.join(root, file)) || read(file) !== expected)
    errors.push(`${file} is stale; run pnpm run docs:generate and review the result.`);
}

const inventory = { tools: tools(), cli: cli(), api: api() };
const mcpBody =
  `Discover the tools in your running instance with \`pnpm run ai -- tools --json\`. Runtime availability depends on Vortex and bearer-token configuration. This reference covers all **${inventory.tools.length}** registrations in the current source.\n\nA token unlocks the token-required tools and makes **every request** require its bearer header. A diagnostic tool can still contact external services: \`check_nexus_mod_updates\` consumes Nexus API quota.\n\n` +
  inventory.tools
    .map(
      (tool) =>
        `## ${tool.name}\n\n${tool.description}\n\n**Availability:** ${tool.tokenRequired ? "Bearer token required." : "Registered without a token; with a configured token, supply it."} [Implementation](${link("src/mcpServer.ts", tool.line)}).\n\n\`\`\`json title="Input schema"\n${JSON.stringify(tool.inputSchema, null, 2)}\n\`\`\`\n`,
    )
    .join("\n");
result(
  "docs/reference/mcp-tools.md",
  "# MCP tool reference\n\n" +
    banner(
      "Use these contracts when calling tools directly or configuring an assistant. See [calling tools](../guides/calling-tools.md) for JSON files, results, errors and state checks.",
    ) +
    mcpBody,
);
result(
  "harness/reference/mcp-tools.md",
  "# MCP registration contracts\n\n" +
    banner(
      "Machine-facing reference. Read the operating manual and the user’s current scope before acting. Human instructions live under /docs.",
    ) +
    mcpBody,
);
const cliBody = `## Command inventory\n\n${inventory.cli.commands.map((name) => "- `" + name + "`").join("\n")}\n\n## Full help\n\n\`\`\`text\n${inventory.cli.help.trim()}\n\`\`\`\n`;
result(
  "docs/reference/cli.md",
  "# CLI reference\n\n" +
    banner(
      "Run commands from the repository root with `pnpm run ai -- <command>`. [Setup](../getting-started/first-session.md), [configuration](configuration.md) and the task guides explain how to use these commands. The text below is generated from the CLI’s own help and dispatch branches, not a separately maintained list.",
    ) +
    cliBody,
);
result(
  "harness/reference/cli.md",
  "# CLI contracts\n\n" +
    banner(
      "Machine-facing inventory and current built-in help. Canonical agent operating rules remain in harness/AGENTS.md; keep human recipes current in /docs.",
    ) +
    cliBody,
);
const apiBody = inventory.api
  .map(
    (module) =>
      `## ${module.name}\n\n[Source](${link(module.file)}). ${module.name === "instance" ? "Only `claimInstanceLease` from this module is re-exported by the scratch-script kit; other symbols here require a direct repository import." : ""}\n\n` +
      module.symbols
        .map(
          (symbol) =>
            (symbol.docs ? symbol.docs + "\n\n" : "") +
            "```typescript\n" +
            symbol.signature +
            "\n```\n\n" +
            `[Implementation](${link(module.file, symbol.line)}).\n`,
        )
        .join("\n"),
  )
  .join("\n");
result(
  "docs/reference/script-api.md",
  "# TypeScript helper reference\n\n" +
    banner(
      "Use [scratch scripts](../guides/scripting.md) for one-off automation and [test writing](../testing/integration.md) for repeatable checks. The kit exposes configuration, MCP, CDP and the namespaces below. Functions and types are generated from their declarations; read the linked implementation for cancellation and lifecycle details. Zip helpers `zipSync`, `unzipSync`, `strToU8`, `strFromU8` are also re-exported from fflate.",
    ) +
    apiBody,
);
result(
  "harness/reference/script-api.md",
  "# Script contracts\n\n" +
    banner(
      "Generated interface reference for specialists. Current human usage and runnable examples belong to /docs.",
    ) +
    apiBody,
);
const packageJson = JSON.parse(read("package.json"));
const scriptsBody = Object.entries(packageJson.scripts)
  .map(([name, command]) => `| \`${name}\` | \`${command.replace(/\|/g, "\\|")}\` |`)
  .join("\n");
result(
  "docs/reference/package-scripts.md",
  "# Package scripts\n\n" +
    banner(
      "Run these from the repository root with `pnpm run <name>`. Test selection, accounts and runtime requirements are explained in [running checks](../testing/running.md) and [benchmarks](../testing/benchmarks.md). A named opt-in script can change its disposable fixture and does not necessarily stop the operator’s already-running app.",
    ) +
    "| Script | Command |\n| --- | --- |\n" +
    scriptsBody +
    "\n",
);
result(
  "harness/reference/package-scripts.md",
  "# Package script contracts\n\n" +
    banner(
      "Source-generated script inventory. Use TESTING.md to determine applicability and update the paired human instructions with behavior changes.",
    ) +
    "| Script | Command |\n| --- | --- |\n" +
    scriptsBody +
    "\n",
);

if (process.argv.includes("--inventory")) {
  const target = path.join(root, "harness/.artifacts/human-docs-20261007/inventory.json");
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, JSON.stringify(inventory, null, 2));
}

if (!write) {
  const map = JSON.parse(read("scripts/documentation-map.json"));
  for (const group of map.groups)
    for (const file of [...group.human, ...group.ai])
      if (!fs.existsSync(path.join(root, file)))
        errors.push(`Missing paired documentation: ${file}`);
  const base = process.env.DOODLEBOT_DOCS_BASE;
  const changed = new Set();
  const git = (args) =>
    cp
      .execFileSync("git", args, { cwd: root, encoding: "utf8" })
      .trim()
      .split(/\r?\n/)
      .filter(Boolean);
  try {
    if (base && !/^0+$/.test(base))
      git(["diff", "--name-only", base + "...HEAD"]).forEach((file) => changed.add(file));
    git(["diff", "--name-only", "HEAD"]).forEach((file) => changed.add(file));
    git(["ls-files", "--others", "--exclude-standard"]).forEach((file) => changed.add(file));
    for (const group of map.groups) {
      if (
        ![...changed].some((file) =>
          group.sources.some((pattern) => new RegExp(pattern).test(file)),
        )
      )
        continue;
      if (!group.human.some((file) => changed.has(file)))
        errors.push(
          `${group.name}: update a mapped human page in the same change (${group.human.join(", ")}).`,
        );
      if (!group.ai.some((file) => changed.has(file)))
        errors.push(
          `${group.name}: update a mapped AI contract/manual in the same change (${group.ai.join(", ")}).`,
        );
    }
    // A shared AI manual covers several areas. A prose-only edit needs the related
    // human explanation, rather than unrelated edits to every guide it happens to index.
    for (const file of changed) {
      const groups = map.groups.filter((group) => group.ai.includes(file));
      if (groups.length && !groups.some((group) => group.human.some((human) => changed.has(human))))
        errors.push(`${file}: update a mapped human companion in the same change.`);
    }
  } catch (error) {
    errors.push("Documentation change accounting failed: " + error.message);
  }
  // Published pages cannot silently link outside the human site to agent instructions.
  const walk = (dir) =>
    fs
      .readdirSync(dir, { withFileTypes: true })
      .flatMap((entry) =>
        entry.isDirectory() ? walk(path.join(dir, entry.name)) : [path.join(dir, entry.name)],
      );
  for (const file of walk(path.join(root, "docs")).filter((file) => file.endsWith(".md"))) {
    const body = fs.readFileSync(file, "utf8");
    if (/\]\([^)]*(?:AGENTS\.md|AGENT-WORKFLOW\.md|KNOWLEDGE-ROUTES\.md|\/\.claude\/)/.test(body))
      errors.push(
        `${path.relative(root, file)} links to AI instructions; explain the operation for human readers instead.`,
      );
  }
  for (const file of ["doodlebot-banner.svg", "doodlebot-logo.svg", "OFL-Manrope.txt"]) {
    if (
      !fs
        .readFileSync(path.join(root, "assets", file))
        .equals(fs.readFileSync(path.join(root, "docs/assets", file)))
    )
      errors.push(
        `docs/assets/${file} differs from the approved assets/${file}; sync the public copy.`,
      );
  }
}
if (errors.length) {
  console.error(errors.join("\n"));
  process.exitCode = 1;
} else
  console.log(
    `${write ? "Generated" : "Checked"} paired documentation: ${inventory.tools.length} MCP tools, ${inventory.cli.commands.length} CLI commands and ${inventory.api.length} helper modules.`,
  );
